export const siteConfig = {
  name: "RayzrSole",
  shortName: "RayzrSole",
  url: "https://rayzrsole.com",
  description:
    "RayzrSole builds AI-powered products, automates workflows, and manages cloud infrastructure so your team can focus on shipping. No DevOps team required.",
  tagline: "Infrastructure that works while you sleep.",
  keywords: [
    "RayzrSole",
    "AI solutions",
    "ML products",
    "workflow automation",
    "cloud infrastructure",
    "DevOps",
    "RPA",
    "API integration",
    "CI/CD pipelines",
    "server management",
    "app development",
    "Kolkata tech company",
    "India AI company",
    "Fazri Analyser",
    "Zync HRMS",
    "campus security AI",
    "P&ID automation",
    "YOLOv8",
    "NRGTech",
    "engineering safety",
  ],
  locale: "en_US",
  twitterHandle: "@rayzrsole",
  email: "contact@rayzrsole.com",
  phone: "+918274828890",
  address: "Kolkata, West Bengal, India",
  baseLinks: {
    home: "/",
  },
}
